create extension if not exists "uuid-ossp";

create table if not exists competitions (
  id bigint generated by default as identity primary key,
  code text unique not null,
  name text not null,
  country text,
  logo text,
  created_at timestamptz default now()
);

create table if not exists teams (
  id bigint generated by default as identity primary key,
  external_id text,
  name text not null,
  short_name text,
  tla text,
  crest text,
  country text,
  created_at timestamptz default now()
);

create table if not exists matches (
  id bigint generated by default as identity primary key,
  external_id text unique,
  competition_id bigint references competitions(id),
  season text,
  match_date timestamptz not null,

  status text not null default 'SCHEDULED',

  home_team_id bigint references teams(id),
  away_team_id bigint references teams(id),

  home_score integer,
  away_score integer,

  venue text,

  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists match_events (
  id bigint generated by default as identity primary key,
  match_id bigint references matches(id) on delete cascade,

  minute integer,
  extra_minute integer,

  event_type text,
  team_id bigint references teams(id),
  player_name text,
  assist_player_name text,

  created_at timestamptz default now()
);

create table if not exists standings (
  id bigint generated by default as identity primary key,
  competition_id bigint references competitions(id),
  season text,

  team_id bigint references teams(id),

  position integer,
  played integer,
  won integer,
  drawn integer,
  lost integer,
  goals_for integer,
  goals_against integer,
  goal_difference integer,
  points integer,

  updated_at timestamptz default now(),

  unique (competition_id, season, team_id)
);

create table if not exists team_statistics (
  id bigint generated by default as identity primary key,

  team_id bigint references teams(id),
  competition_id bigint references competitions(id),
  season text,

  matches_played integer default 0,

  goals_for integer default 0,
  goals_against integer default 0,

  wins integer default 0,
  draws integer default 0,
  losses integer default 0,

  clean_sheets integer default 0,
  failed_to_score integer default 0,

  home_goals_for integer default 0,
  home_goals_against integer default 0,

  away_goals_for integer default 0,
  away_goals_against integer default 0,

  updated_at timestamptz default now(),

  unique (team_id, competition_id, season)
);

create table if not exists predictions (
  id bigint generated by default as identity primary key,

  match_id bigint references matches(id) on delete cascade,

  home_win_probability numeric,
  draw_probability numeric,
  away_win_probability numeric,

  over_15_probability numeric,
  over_25_probability numeric,
  over_35_probability numeric,

  btts_probability numeric,

  predicted_home_goals numeric,
  predicted_away_goals numeric,

  predicted_score text,

  model_version text,

  created_at timestamptz default now(),

  unique (match_id, model_version)
);

create index if not exists matches_date_idx
on matches(match_date);

create index if not exists matches_status_idx
on matches(status);

create index if not exists matches_home_team_idx
on matches(home_team_id);

create index if not exists matches_away_team_idx
on matches(away_team_id);

create index if not exists match_events_match_idx
on match_events(match_id);

create index if not exists predictions_match_idx
on predictions(match_id);
